name: Security and Compliance

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v3 # Use the latest version supporting Node.js 20

    # Runs Gitleaks to scan your code for secrets
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2.3.4
      # Ensure you use the latest version or one that's compatible with Node.js 20
      # Add any required configuration for Gitleaks here
